services:
  - type: web
    name: osrs-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python simple_server.py"
    envVars:
      - key: DISPLAY
        value: ":99"
